### ISSUE TITLE
Can't Run Published Site - alternative-spa-template

### ISSUE THREAD

**Issue by mzhukovs** [DaniJG/ASPCoreVueCLITemplates#4] opened 2020-03-06 18:33 UTC
If I build the alternative-spa-template in release mode then go to output and run "dotnet VueSPATemplate.dll" command, it says the app started on localhost:5001 but then nothing comes up (page not found) - am I just missing something obvious?

**Comment by DaniJG** [comment] 2020-03-09 12:40
The published site was intended to work in the same way as for out of the box Angular/React templates.

A couple of sanity checks:

- Make sure you did run `dotnet publish`, so you can see a `ClientApp/dist` folder inside the `bin/Release/netcoreapp3.0/publish/` folder.
- Make sure you are running the `dotnet run VueSPATemplate.dll` from inside that publish folder

When I do that the site starts on https://localhost:5001 however it does not automatically load the index page so I have to force loading `https://localhost:5001/index.html` in the browser.

Did a quick check and its due to the missing `app.UseSpa` as part of the `Startup.Configure method`. Will try to do some more testing before updating the project, but in the meantime give it a try converting the following lines:
```
if (env.IsDevelopment())
{
    app.UseVueDevelopmentServer();
}
```
into:
```
if (env.IsDevelopment())
{
    app.UseVueDevelopmentServer();
}
else
{
  app.UseSpa(spa =>
  {
      spa.Options.SourcePath = "ClientApp";
  });
}
```

**Comment by DaniJG** [comment] 2020-03-14 17:20
Will close the issue after that PR, but let me know if you run into further issues

**Closed by DaniJG** 2020-03-14 17:20 UTC

**Comment by godshades** [comment] 2020-06-12 10:36
@DaniJG hi, I'm trying publish this alternative to centos7 and apache server
my FrontEnd work OK, my .net sever running on localhost:5000 OK
but when call api from FE it doesn't work - return 404 not found
Do I need config something else ?

**Comment by DaniJG** [comment] 2020-06-15 09:14
Assuming you already have the fixes above added as part of the original issue, try publishing to a local folder and running the published site from there. If you cant reproduce the issue this way, it could be something specific to your hosting/server setup.
```
dotnet publish -c Release
cd bin/Release/netcoreapp3.0/publish
dotnet VueSPATemplate.dll
```

When you do this, the application runs on `https://localhost:5001` (with redirect to HTTPS from `http://localhost:5000`), where the Vue client side is just a set of static files served from the `ClientApp/dist` folder. 

Other things that might be worth considering:
- Check the browser logs (specially console and network) and the server side logs (which particular requests succeed and which ones dont. Is there any that doesnt even reach the server?)
- Can you successfully reach your API using curl or postman?
- Have you tried publishing this template as is, versus any extra code/modifiactions you might have added?

**Comment by godshades** [comment] 2020-06-16 01:41
@DaniJG thanks for your advice. I was misunderstood about hosting .netcore
Before I think need host 1 port for client view, 1 port for api server
I just do like you said + https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-3.1 => I face 503 error
After google I found "setsebool -P httpd_can_network_connect 1" and everything working now

**Comment by DaniJG** [comment] 2020-06-16 14:34
awesome, great to know!
